import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { defineConfig, type Plugin } from 'vite';

// Where the deployed bundle lives. The E1004's shell loads device-boot.js from
// here; tests override it to point at a local static server.
const DEPLOY_BASE = process.env.DEVICE_BOOT_BASE ?? 'https://elohmeier.github.io/reterm/';

/**
 * Emits build/device-boot.js: a stable, unhashed loader the firmware shell can
 * reference forever. It injects the current hashed CSS and dynamic-imports the
 * hashed entry module, which then executes in the including page's origin so
 * device-served uploads stay same-origin on iOS Safari.
 */
function deviceBoot(): Plugin {
  return {
    name: 'reterm-device-boot',
    apply: 'build',
    async closeBundle() {
      const manifest = JSON.parse(await readFile('build/.vite/manifest.json', 'utf8'));
      const entry = manifest['index.html'];
      if (!entry) throw new Error('index.html entry missing from Vite manifest');
      const css: string[] = entry.css ?? [];
      const boot = `// Generated by vite.config.ts on every build. Loaded by the E1004's HTML
// shell; keep the URL stable and bump its ?v= only with paired firmware
// changes (see AGENTS.md).
(function () {
  var base = ${JSON.stringify(DEPLOY_BASE)};
  ${JSON.stringify(css)}.forEach(function (href) {
    var link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = base + href;
    document.head.appendChild(link);
  });
  import(base + ${JSON.stringify(entry.file)}).catch(function () {
    var app = document.getElementById('app');
    if (app) app.textContent = 'Could not fetch the editor from the internet. Give this phone internet access, then reload.';
  });
})();
`;
      await writeFile('build/device-boot.js', boot);
    }
  };
}

export default defineConfig(({ command }) => ({
  base: command === 'build' ? '/reterm/' : '/',
  publicDir: false,
  resolve: {
    alias: { $lib: '/src/lib' }
  },
  build: {
    outDir: 'build',
    manifest: true,
    rollupOptions: {
      input: {
        index: resolve(import.meta.dirname, 'index.html'),
        flash: resolve(import.meta.dirname, 'flash.html')
      }
    }
  },
  plugins: [svelte(), deviceBoot()]
}));
